// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightTracker.Infrastructure.Context;

#nullable disable

namespace WeightTracker.Infrastructure.Migrations
{
    [DbContext(typeof(WeightTrackerDbContext))]
    [Migration("20251130102836_AddVersionInfoTable")]
    partial class AddVersionInfoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WeightTracker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ResetCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Records", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = new Guid("83e2658f-30dd-456f-9901-791c36e16fa1"),
                            CreatedAt = new DateTime(2025, 8, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 8, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 85.95m
                        },
                        new
                        {
                            RecordId = new Guid("e87c6b04-2eed-4fb7-9a2a-b70fd3467b86"),
                            CreatedAt = new DateTime(2025, 9, 2, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 2, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 84.64m
                        },
                        new
                        {
                            RecordId = new Guid("87bd51c9-bd2d-403a-8198-c7d4eaba1c58"),
                            CreatedAt = new DateTime(2025, 9, 5, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 5, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 85.32m
                        },
                        new
                        {
                            RecordId = new Guid("76a9b4de-7c07-4abf-817b-126b4636dc60"),
                            CreatedAt = new DateTime(2025, 9, 8, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 8, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 84.01m
                        },
                        new
                        {
                            RecordId = new Guid("e1f90509-51ba-4993-b709-4f2945b156dd"),
                            CreatedAt = new DateTime(2025, 9, 11, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 11, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 84.69m
                        },
                        new
                        {
                            RecordId = new Guid("fbef0461-efaa-45d6-860c-450486430f40"),
                            CreatedAt = new DateTime(2025, 9, 14, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 14, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 83.38m
                        },
                        new
                        {
                            RecordId = new Guid("27f0ac37-663d-45b0-92eb-12f5bcc369a8"),
                            CreatedAt = new DateTime(2025, 9, 17, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 17, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 82.06m
                        },
                        new
                        {
                            RecordId = new Guid("a93039d7-7c64-4730-8e44-c936704eebe2"),
                            CreatedAt = new DateTime(2025, 9, 20, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 20, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 82.74m
                        },
                        new
                        {
                            RecordId = new Guid("c7bb9611-6fdc-4680-8c69-b8589c1ba2ea"),
                            CreatedAt = new DateTime(2025, 9, 23, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 23, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 81.43m
                        },
                        new
                        {
                            RecordId = new Guid("81780cdc-2a07-4187-b9ac-dac40779550c"),
                            CreatedAt = new DateTime(2025, 9, 26, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 26, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 82.11m
                        },
                        new
                        {
                            RecordId = new Guid("5374fbc4-c0af-4d0a-8e04-120f267990a4"),
                            CreatedAt = new DateTime(2025, 9, 29, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 29, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 80.80m
                        },
                        new
                        {
                            RecordId = new Guid("6a9a6eaf-d7b1-4c63-9053-f40555ff3688"),
                            CreatedAt = new DateTime(2025, 10, 2, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 2, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 81.48m
                        },
                        new
                        {
                            RecordId = new Guid("d46e4ed5-af9b-4bb3-8e6f-81dfc62f558b"),
                            CreatedAt = new DateTime(2025, 10, 5, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 5, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 80.17m
                        },
                        new
                        {
                            RecordId = new Guid("f3905b21-a4be-4902-8404-872b4e480057"),
                            CreatedAt = new DateTime(2025, 10, 8, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 8, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 78.85m
                        },
                        new
                        {
                            RecordId = new Guid("a00685ed-0a91-4345-b82f-87e10c792885"),
                            CreatedAt = new DateTime(2025, 10, 11, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 11, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 79.54m
                        },
                        new
                        {
                            RecordId = new Guid("833fb3e7-fff5-46af-aaca-c9ebd80fcbc7"),
                            CreatedAt = new DateTime(2025, 10, 14, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 14, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 78.22m
                        },
                        new
                        {
                            RecordId = new Guid("7f921c8b-616e-4bb5-ba98-099a93794d4e"),
                            CreatedAt = new DateTime(2025, 10, 17, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 17, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 78.91m
                        },
                        new
                        {
                            RecordId = new Guid("61c30cff-c920-412d-a4e3-a7e5411f6364"),
                            CreatedAt = new DateTime(2025, 10, 20, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 20, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 77.59m
                        },
                        new
                        {
                            RecordId = new Guid("797c6723-892c-48a3-8170-c066c2c39847"),
                            CreatedAt = new DateTime(2025, 10, 23, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 23, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 78.27m
                        },
                        new
                        {
                            RecordId = new Guid("7cf54841-776b-474e-b14b-125a06e041ee"),
                            CreatedAt = new DateTime(2025, 10, 26, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 26, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 76.96m
                        },
                        new
                        {
                            RecordId = new Guid("b154aec4-f1f4-4d37-96a9-725d0765f9f2"),
                            CreatedAt = new DateTime(2025, 10, 29, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 29, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 75.64m
                        },
                        new
                        {
                            RecordId = new Guid("4678745d-c623-475e-8acd-6a353b7305e8"),
                            CreatedAt = new DateTime(2025, 11, 1, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 1, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 76.33m
                        },
                        new
                        {
                            RecordId = new Guid("fde7b5e7-ecdb-48cd-91c0-713b846a9809"),
                            CreatedAt = new DateTime(2025, 11, 4, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 4, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 75.01m
                        },
                        new
                        {
                            RecordId = new Guid("247a91ca-b6a1-4133-8eb8-91fb54a9f8d3"),
                            CreatedAt = new DateTime(2025, 11, 7, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 7, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 75.70m
                        },
                        new
                        {
                            RecordId = new Guid("360253d6-44db-481f-aea8-a2a0bffed02b"),
                            CreatedAt = new DateTime(2025, 11, 10, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 10, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 74.38m
                        },
                        new
                        {
                            RecordId = new Guid("ca215b05-8b44-4d4c-a410-1b85d073ed4b"),
                            CreatedAt = new DateTime(2025, 11, 13, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 13, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 75.07m
                        },
                        new
                        {
                            RecordId = new Guid("56dae0f0-c48c-4c96-a9e1-59f9fc8f1d41"),
                            CreatedAt = new DateTime(2025, 11, 16, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 16, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 73.75m
                        },
                        new
                        {
                            RecordId = new Guid("55537c0d-e640-4dc9-bb74-bd12c7ecb52b"),
                            CreatedAt = new DateTime(2025, 11, 19, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 19, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 72.44m
                        },
                        new
                        {
                            RecordId = new Guid("b8c87ce1-e411-4d10-b5a0-0db6aaf9f2a9"),
                            CreatedAt = new DateTime(2025, 11, 22, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 22, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 73.12m
                        },
                        new
                        {
                            RecordId = new Guid("85373136-7c0f-49bb-8b94-e9f3cab49381"),
                            CreatedAt = new DateTime(2025, 11, 25, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 25, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9355),
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            Weight = 71.80m
                        },
                        new
                        {
                            RecordId = new Guid("b76a9b6a-7b93-4a74-9952-645b5a15c7a6"),
                            CreatedAt = new DateTime(2025, 9, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 9, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 67.68m
                        },
                        new
                        {
                            RecordId = new Guid("70bf7613-2d84-4f48-ba01-d36556afb384"),
                            CreatedAt = new DateTime(2025, 10, 4, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 4, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 68.13m
                        },
                        new
                        {
                            RecordId = new Guid("4a0d3af8-063a-420a-923e-12f07a8a1788"),
                            CreatedAt = new DateTime(2025, 10, 8, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 8, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 68.59m
                        },
                        new
                        {
                            RecordId = new Guid("104b9adf-ad35-4ce5-be37-6a37b11bee5d"),
                            CreatedAt = new DateTime(2025, 10, 12, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 12, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 69.04m
                        },
                        new
                        {
                            RecordId = new Guid("0311bfc2-7c34-410e-8979-ecc9393fed71"),
                            CreatedAt = new DateTime(2025, 10, 16, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 16, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 69.50m
                        },
                        new
                        {
                            RecordId = new Guid("d654dd0a-eb76-4816-b337-80b62deffa46"),
                            CreatedAt = new DateTime(2025, 10, 20, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 20, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 69.95m
                        },
                        new
                        {
                            RecordId = new Guid("54f3a369-cab5-4f3a-b295-7e0ddbe9fbee"),
                            CreatedAt = new DateTime(2025, 10, 24, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 24, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 70.40m
                        },
                        new
                        {
                            RecordId = new Guid("f0822e97-96a4-4d1e-83da-95fbdee14a28"),
                            CreatedAt = new DateTime(2025, 10, 28, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 28, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 70.86m
                        },
                        new
                        {
                            RecordId = new Guid("e01c7163-06e2-4220-ba2d-47417b1f148b"),
                            CreatedAt = new DateTime(2025, 11, 1, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 1, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 71.31m
                        },
                        new
                        {
                            RecordId = new Guid("40eac4c9-b61e-4949-9ed5-f896f1774795"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 5, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 71.77m
                        },
                        new
                        {
                            RecordId = new Guid("df38bea7-1a8d-48a8-8f68-72314def0a15"),
                            CreatedAt = new DateTime(2025, 11, 9, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 9, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 70.72m
                        },
                        new
                        {
                            RecordId = new Guid("372541a5-f2ee-4217-ba96-fd7937819a2a"),
                            CreatedAt = new DateTime(2025, 11, 13, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 13, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 71.18m
                        },
                        new
                        {
                            RecordId = new Guid("5e801f1e-c74d-4418-a89e-c86e9fcfe08c"),
                            CreatedAt = new DateTime(2025, 11, 17, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 17, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 71.63m
                        },
                        new
                        {
                            RecordId = new Guid("0c9b90c6-4ce3-4f65-8835-53e1312eb811"),
                            CreatedAt = new DateTime(2025, 11, 21, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 21, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 72.09m
                        },
                        new
                        {
                            RecordId = new Guid("b7603c2d-f869-4f8c-b0f1-b79bad3c7e78"),
                            CreatedAt = new DateTime(2025, 11, 25, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 25, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(9850),
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            Weight = 72.54m
                        },
                        new
                        {
                            RecordId = new Guid("93dc53b7-d302-43bc-b156-d5373cf58dd4"),
                            CreatedAt = new DateTime(2025, 10, 30, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 10, 30, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 92.99m
                        },
                        new
                        {
                            RecordId = new Guid("9af545c5-c874-4535-b1ba-a709594ae38b"),
                            CreatedAt = new DateTime(2025, 11, 1, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 1, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 92.60m
                        },
                        new
                        {
                            RecordId = new Guid("cd5bce8b-1b56-4403-94aa-2654e309fe1b"),
                            CreatedAt = new DateTime(2025, 11, 3, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 3, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 92.22m
                        },
                        new
                        {
                            RecordId = new Guid("54cd4972-ea9f-4306-a541-5176db5edfa7"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 5, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 91.83m
                        },
                        new
                        {
                            RecordId = new Guid("a59fa099-58c3-40f7-aa5a-c1af2ea6bbb8"),
                            CreatedAt = new DateTime(2025, 11, 7, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 7, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 91.44m
                        },
                        new
                        {
                            RecordId = new Guid("dcb55d7b-d42a-4ab2-ba38-4d5d59f66f3f"),
                            CreatedAt = new DateTime(2025, 11, 9, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 9, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 91.05m
                        },
                        new
                        {
                            RecordId = new Guid("01736a3e-a98d-4fd8-ac3e-09cdf673f4ea"),
                            CreatedAt = new DateTime(2025, 11, 11, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 11, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 90.66m
                        },
                        new
                        {
                            RecordId = new Guid("c379fe1e-91bc-4bac-83e7-086ed24831b9"),
                            CreatedAt = new DateTime(2025, 11, 13, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 13, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 90.28m
                        },
                        new
                        {
                            RecordId = new Guid("b2780c90-8a3a-436e-90ca-e6593d2c8b9f"),
                            CreatedAt = new DateTime(2025, 11, 15, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 15, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 89.89m
                        },
                        new
                        {
                            RecordId = new Guid("f904e0e1-e627-4115-91ed-e77161dd3905"),
                            CreatedAt = new DateTime(2025, 11, 17, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 17, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 89.50m
                        },
                        new
                        {
                            RecordId = new Guid("0f42f30d-703d-4fc8-b22b-fb1b14be5287"),
                            CreatedAt = new DateTime(2025, 11, 19, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 19, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 86.61m
                        },
                        new
                        {
                            RecordId = new Guid("779dc9e5-a548-471c-8543-2bfbf261ce10"),
                            CreatedAt = new DateTime(2025, 11, 21, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 21, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 86.23m
                        },
                        new
                        {
                            RecordId = new Guid("a78beff4-f1d4-4a9c-9ae3-290ba5ef02c2"),
                            CreatedAt = new DateTime(2025, 11, 23, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 23, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 85.84m
                        },
                        new
                        {
                            RecordId = new Guid("9416b23f-448d-45f1-ab43-385c042f9cc4"),
                            CreatedAt = new DateTime(2025, 11, 25, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 25, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 85.45m
                        },
                        new
                        {
                            RecordId = new Guid("d1cf81f5-9613-4122-9cfe-72a94dd7dfc6"),
                            CreatedAt = new DateTime(2025, 11, 27, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 27, 10, 28, 36, 53, DateTimeKind.Utc).AddTicks(62),
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            Weight = 85.06m
                        });
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("f42718c1-552d-4015-8577-4d3d423f4766"),
                            CreatedAt = new DateTime(2025, 5, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(8290),
                            Email = "john.doe@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$SDUcLaLfkzQL7OlzLhlhSORCX8VNsMiNdOrkx81UzuCILr9ugv5X.",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserId = new Guid("4fb446ba-9962-4aae-8f59-8b296d22b949"),
                            CreatedAt = new DateTime(2025, 7, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(8305),
                            Email = "jane.smith@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$SDUcLaLfkzQL7OlzLhlhSORCX8VNsMiNdOrkx81UzuCILr9ugv5X.",
                            Username = "jane_smith"
                        },
                        new
                        {
                            UserId = new Guid("04cfe11d-8bdf-4cc7-b4ac-c9304be7f9d3"),
                            CreatedAt = new DateTime(2025, 9, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(8308),
                            Email = "mike.johnson@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$SDUcLaLfkzQL7OlzLhlhSORCX8VNsMiNdOrkx81UzuCILr9ugv5X.",
                            Username = "mike_johnson"
                        },
                        new
                        {
                            UserId = new Guid("c4248a1e-a005-4896-bc0f-7025e8afde47"),
                            CreatedAt = new DateTime(2025, 10, 30, 10, 28, 36, 52, DateTimeKind.Utc).AddTicks(8478),
                            Email = "admin@email.com",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$SDUcLaLfkzQL7OlzLhlhSORCX8VNsMiNdOrkx81UzuCILr9ugv5X.",
                            Username = "admin_user"
                        });
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.VersionInfo", b =>
                {
                    b.Property<int>("VersionInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("VersionInfoId");

                    b.ToTable("VersionHistory");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("WeightTracker.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Records", b =>
                {
                    b.HasOne("WeightTracker.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
