// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightTracker.Infrastructure.Context;

#nullable disable

namespace WeightTracker.Infrastructure.Migrations
{
    [DbContext(typeof(WeightTrackerDbContext))]
    [Migration("20251211125241_AddGoogleAuthFields")]
    partial class AddGoogleAuthFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WeightTracker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ResetCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Records", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = new Guid("1348e6e3-5906-4ac1-a47f-8c17b52c0e91"),
                            CreatedAt = new DateTime(2025, 9, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 85.95m
                        },
                        new
                        {
                            RecordId = new Guid("6b7b1c43-3800-4f75-ba3d-d237da578ca3"),
                            CreatedAt = new DateTime(2025, 9, 14, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 14, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 84.64m
                        },
                        new
                        {
                            RecordId = new Guid("11d42163-fe28-43d8-b54a-2704e4de07c0"),
                            CreatedAt = new DateTime(2025, 9, 17, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 17, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 85.32m
                        },
                        new
                        {
                            RecordId = new Guid("8f8f48db-a2f9-494f-a84d-8e67b9bfa54b"),
                            CreatedAt = new DateTime(2025, 9, 20, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 20, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 84.01m
                        },
                        new
                        {
                            RecordId = new Guid("a448e1b6-825e-4175-98cb-796c77cebd44"),
                            CreatedAt = new DateTime(2025, 9, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 84.69m
                        },
                        new
                        {
                            RecordId = new Guid("db6e8e95-44fd-4ea0-a90c-56acd519907a"),
                            CreatedAt = new DateTime(2025, 9, 26, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 26, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 83.38m
                        },
                        new
                        {
                            RecordId = new Guid("3aaa3a97-87f2-4bde-85d9-a52d0fafee7b"),
                            CreatedAt = new DateTime(2025, 9, 29, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 29, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 82.06m
                        },
                        new
                        {
                            RecordId = new Guid("b40ff037-3662-4282-8274-b0159a1ac06e"),
                            CreatedAt = new DateTime(2025, 10, 2, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 2, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 82.74m
                        },
                        new
                        {
                            RecordId = new Guid("77841c36-c502-4091-abfd-67d224f81c4f"),
                            CreatedAt = new DateTime(2025, 10, 5, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 5, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 81.43m
                        },
                        new
                        {
                            RecordId = new Guid("9ac5dd86-fe65-4602-aa35-79d9a7f24dee"),
                            CreatedAt = new DateTime(2025, 10, 8, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 8, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 82.11m
                        },
                        new
                        {
                            RecordId = new Guid("c6255fd6-fef9-4f41-ba6f-cc4c5df2bc9f"),
                            CreatedAt = new DateTime(2025, 10, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 80.80m
                        },
                        new
                        {
                            RecordId = new Guid("78a54921-2eb8-4001-bba4-a5c53c76c224"),
                            CreatedAt = new DateTime(2025, 10, 14, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 14, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 81.48m
                        },
                        new
                        {
                            RecordId = new Guid("50731aae-aeba-44f5-8dab-1d67646d3544"),
                            CreatedAt = new DateTime(2025, 10, 17, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 17, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 80.17m
                        },
                        new
                        {
                            RecordId = new Guid("6b931919-9b4c-4bc5-b80c-c24dfb72e85e"),
                            CreatedAt = new DateTime(2025, 10, 20, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 20, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 78.85m
                        },
                        new
                        {
                            RecordId = new Guid("cb044c29-cdf9-4c7b-9cff-f7171099c2c2"),
                            CreatedAt = new DateTime(2025, 10, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 79.54m
                        },
                        new
                        {
                            RecordId = new Guid("efe9b67d-e68f-420e-a1a4-7b82a31fd4c4"),
                            CreatedAt = new DateTime(2025, 10, 26, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 26, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 78.22m
                        },
                        new
                        {
                            RecordId = new Guid("09122ffe-7b8f-4031-af8d-907cac46f4be"),
                            CreatedAt = new DateTime(2025, 10, 29, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 29, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 78.91m
                        },
                        new
                        {
                            RecordId = new Guid("db2aaa2e-1fb0-4ded-9bd5-2fa84866cf4b"),
                            CreatedAt = new DateTime(2025, 11, 1, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 1, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 77.59m
                        },
                        new
                        {
                            RecordId = new Guid("8cbad47a-5c48-4953-9d43-f1138cd6243f"),
                            CreatedAt = new DateTime(2025, 11, 4, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 4, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 78.27m
                        },
                        new
                        {
                            RecordId = new Guid("d38f8d51-f2e4-4192-9a24-4f0c7f7cadcc"),
                            CreatedAt = new DateTime(2025, 11, 7, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 7, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 76.96m
                        },
                        new
                        {
                            RecordId = new Guid("65284d36-9ada-4b68-94a1-7795c391b033"),
                            CreatedAt = new DateTime(2025, 11, 10, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 10, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 75.64m
                        },
                        new
                        {
                            RecordId = new Guid("ef930129-d5fa-417b-b36c-6064320058ce"),
                            CreatedAt = new DateTime(2025, 11, 13, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 13, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 76.33m
                        },
                        new
                        {
                            RecordId = new Guid("67a6399e-fc72-4517-a77d-fa0f14ec031c"),
                            CreatedAt = new DateTime(2025, 11, 16, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 16, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 75.01m
                        },
                        new
                        {
                            RecordId = new Guid("d95b5184-5ab7-4274-a1f7-e9c4ce80adcb"),
                            CreatedAt = new DateTime(2025, 11, 19, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 19, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 75.70m
                        },
                        new
                        {
                            RecordId = new Guid("2f0a3abd-e2bb-4ec6-9625-b70765b37f2e"),
                            CreatedAt = new DateTime(2025, 11, 22, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 22, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 74.38m
                        },
                        new
                        {
                            RecordId = new Guid("a5f604cf-6c04-4c6f-9444-b2cba6918642"),
                            CreatedAt = new DateTime(2025, 11, 25, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 25, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 75.07m
                        },
                        new
                        {
                            RecordId = new Guid("1aa4135b-55b9-42e6-9d75-0f4eacd27e6f"),
                            CreatedAt = new DateTime(2025, 11, 28, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 28, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 73.75m
                        },
                        new
                        {
                            RecordId = new Guid("2ef94088-46b2-4109-a813-6ea9b528c10e"),
                            CreatedAt = new DateTime(2025, 12, 1, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 12, 1, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 72.44m
                        },
                        new
                        {
                            RecordId = new Guid("a553c273-9a52-4b35-8da5-eedaa67e81b9"),
                            CreatedAt = new DateTime(2025, 12, 4, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 12, 4, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 73.12m
                        },
                        new
                        {
                            RecordId = new Guid("54becfbf-443d-46d6-a498-a8f4503b1a01"),
                            CreatedAt = new DateTime(2025, 12, 7, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 12, 7, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(7430),
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            Weight = 71.80m
                        },
                        new
                        {
                            RecordId = new Guid("649fb5a7-eede-4a11-b0e0-bc5f086cd79e"),
                            CreatedAt = new DateTime(2025, 10, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 67.68m
                        },
                        new
                        {
                            RecordId = new Guid("cd6fecaa-21d3-4007-b533-bab451a7c03a"),
                            CreatedAt = new DateTime(2025, 10, 15, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 15, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 68.13m
                        },
                        new
                        {
                            RecordId = new Guid("8711f2be-7f45-45e4-83e8-4be8abf492ca"),
                            CreatedAt = new DateTime(2025, 10, 19, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 19, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 68.59m
                        },
                        new
                        {
                            RecordId = new Guid("22650119-a421-44d5-bfb7-e3591a1f2691"),
                            CreatedAt = new DateTime(2025, 10, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 69.04m
                        },
                        new
                        {
                            RecordId = new Guid("fcb1efad-6834-477f-9998-560adb4de843"),
                            CreatedAt = new DateTime(2025, 10, 27, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 27, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 69.50m
                        },
                        new
                        {
                            RecordId = new Guid("82517dba-ed14-47e9-9b58-dba2e446aa5d"),
                            CreatedAt = new DateTime(2025, 10, 31, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 31, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 69.95m
                        },
                        new
                        {
                            RecordId = new Guid("259f8874-7811-4522-852e-06c806c9b177"),
                            CreatedAt = new DateTime(2025, 11, 4, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 4, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 70.40m
                        },
                        new
                        {
                            RecordId = new Guid("6401aba5-9d85-47cb-a9e3-3f85c359d656"),
                            CreatedAt = new DateTime(2025, 11, 8, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 8, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 70.86m
                        },
                        new
                        {
                            RecordId = new Guid("565bf3b0-3350-4b31-be2b-664f5f995108"),
                            CreatedAt = new DateTime(2025, 11, 12, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 12, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 71.31m
                        },
                        new
                        {
                            RecordId = new Guid("269bf952-e1c7-4f2b-99a3-6a34b59ec093"),
                            CreatedAt = new DateTime(2025, 11, 16, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 16, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 71.77m
                        },
                        new
                        {
                            RecordId = new Guid("06cbc73f-88be-4b45-b26b-c90d1c408878"),
                            CreatedAt = new DateTime(2025, 11, 20, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 20, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 70.72m
                        },
                        new
                        {
                            RecordId = new Guid("a7ddd19d-94d9-4a82-a9aa-27e5a3614554"),
                            CreatedAt = new DateTime(2025, 11, 24, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 24, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 71.18m
                        },
                        new
                        {
                            RecordId = new Guid("86ec0d23-9166-4642-90bd-9eff7c355b5d"),
                            CreatedAt = new DateTime(2025, 11, 28, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 28, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 71.63m
                        },
                        new
                        {
                            RecordId = new Guid("b21338b1-e8ba-4825-b30f-79d9f839ff01"),
                            CreatedAt = new DateTime(2025, 12, 2, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 12, 2, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 72.09m
                        },
                        new
                        {
                            RecordId = new Guid("e12bc4f4-643e-42b8-a67b-3571ce5e2716"),
                            CreatedAt = new DateTime(2025, 12, 6, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 12, 6, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8086),
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            Weight = 72.54m
                        },
                        new
                        {
                            RecordId = new Guid("4f85a0f1-0ef9-4fe9-bcbc-5ea39c1db4a4"),
                            CreatedAt = new DateTime(2025, 11, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 92.99m
                        },
                        new
                        {
                            RecordId = new Guid("c06f9435-62cc-4c6b-ab33-864b66340e84"),
                            CreatedAt = new DateTime(2025, 11, 13, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 13, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 92.60m
                        },
                        new
                        {
                            RecordId = new Guid("93333d6d-f70f-4a39-90ef-91220b9058b8"),
                            CreatedAt = new DateTime(2025, 11, 15, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 15, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 92.22m
                        },
                        new
                        {
                            RecordId = new Guid("dea8bf56-f3da-45cb-992e-457349640b4e"),
                            CreatedAt = new DateTime(2025, 11, 17, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 17, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 91.83m
                        },
                        new
                        {
                            RecordId = new Guid("b3d9e5ec-feec-49da-aac4-38ba323b6db3"),
                            CreatedAt = new DateTime(2025, 11, 19, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 19, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 91.44m
                        },
                        new
                        {
                            RecordId = new Guid("9979db5a-bd1d-4782-9fc8-d12b0a338bfe"),
                            CreatedAt = new DateTime(2025, 11, 21, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 21, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 91.05m
                        },
                        new
                        {
                            RecordId = new Guid("99a3672e-7aa3-4f67-8529-36719aba681e"),
                            CreatedAt = new DateTime(2025, 11, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 23, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 90.66m
                        },
                        new
                        {
                            RecordId = new Guid("bac08e27-88b1-4c30-a9bf-dcffe50248e2"),
                            CreatedAt = new DateTime(2025, 11, 25, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 25, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 90.28m
                        },
                        new
                        {
                            RecordId = new Guid("278315b7-6e50-4627-a11b-069cd8515123"),
                            CreatedAt = new DateTime(2025, 11, 27, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 27, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 89.89m
                        },
                        new
                        {
                            RecordId = new Guid("e82531f9-6a33-4ef9-a3dc-0155c1d985fa"),
                            CreatedAt = new DateTime(2025, 11, 29, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 29, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 89.50m
                        },
                        new
                        {
                            RecordId = new Guid("937c609f-2ba9-406a-a1a1-97bb18edc2c2"),
                            CreatedAt = new DateTime(2025, 12, 1, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 1, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 86.61m
                        },
                        new
                        {
                            RecordId = new Guid("061164ed-5be3-4037-9e91-135a4b937ae6"),
                            CreatedAt = new DateTime(2025, 12, 3, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 3, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 86.23m
                        },
                        new
                        {
                            RecordId = new Guid("bd075c31-01c2-4fd0-a877-3220076dd2cc"),
                            CreatedAt = new DateTime(2025, 12, 5, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 5, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 85.84m
                        },
                        new
                        {
                            RecordId = new Guid("9ca09276-bdf3-4db0-a3d1-694b2b8d674c"),
                            CreatedAt = new DateTime(2025, 12, 7, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 7, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 85.45m
                        },
                        new
                        {
                            RecordId = new Guid("3f55e15f-9bbe-4564-88cb-116372f33ee4"),
                            CreatedAt = new DateTime(2025, 12, 9, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 9, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(8302),
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            Weight = 85.06m
                        });
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c3f2a699-fe97-48f6-a9fc-698c2d672209"),
                            CreatedAt = new DateTime(2025, 6, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(6839),
                            Email = "john.doe@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$xh9TXJ4xtwOG/Jr0mebdzO3YinVaeN9un5O2HUBKX05QPM4xwQfnO",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserId = new Guid("8f851f2a-6cdf-413d-80d9-4b5244c75f0a"),
                            CreatedAt = new DateTime(2025, 8, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(6855),
                            Email = "jane.smith@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$xh9TXJ4xtwOG/Jr0mebdzO3YinVaeN9un5O2HUBKX05QPM4xwQfnO",
                            Username = "jane_smith"
                        },
                        new
                        {
                            UserId = new Guid("52813db3-3d79-4af0-ae63-29342ed28f27"),
                            CreatedAt = new DateTime(2025, 10, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(6856),
                            Email = "mike.johnson@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$xh9TXJ4xtwOG/Jr0mebdzO3YinVaeN9un5O2HUBKX05QPM4xwQfnO",
                            Username = "mike_johnson"
                        },
                        new
                        {
                            UserId = new Guid("cacdde49-bb86-4104-9925-1ae1b32e4589"),
                            CreatedAt = new DateTime(2025, 11, 11, 12, 52, 41, 506, DateTimeKind.Utc).AddTicks(6857),
                            Email = "admin@email.com",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$xh9TXJ4xtwOG/Jr0mebdzO3YinVaeN9un5O2HUBKX05QPM4xwQfnO",
                            Username = "admin_user"
                        });
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.VersionInfo", b =>
                {
                    b.Property<int>("VersionInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("VersionInfoId");

                    b.ToTable("VersionHistory");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("WeightTracker.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Records", b =>
                {
                    b.HasOne("WeightTracker.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
