// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightTracker.Infrastructure.Context;

#nullable disable

namespace WeightTracker.Infrastructure.Migrations
{
    [DbContext(typeof(WeightTrackerDbContext))]
    [Migration("20251209100930_GoogleAuth")]
    partial class GoogleAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WeightTracker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ResetCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Records", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = new Guid("1b35cdde-3cf8-4efb-ab03-e338484a1b9a"),
                            CreatedAt = new DateTime(2025, 9, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 85.95m
                        },
                        new
                        {
                            RecordId = new Guid("099894da-8e9a-4072-a185-e1659a38bd07"),
                            CreatedAt = new DateTime(2025, 9, 12, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 12, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 84.64m
                        },
                        new
                        {
                            RecordId = new Guid("5009dc89-d116-4a00-b2bf-cd924d3bf364"),
                            CreatedAt = new DateTime(2025, 9, 15, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 15, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 85.32m
                        },
                        new
                        {
                            RecordId = new Guid("b1f6e662-3dd6-4b87-902c-e9f02df0d5a5"),
                            CreatedAt = new DateTime(2025, 9, 18, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 18, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 84.01m
                        },
                        new
                        {
                            RecordId = new Guid("7d0fdb49-5675-446e-a319-8edd96ea166a"),
                            CreatedAt = new DateTime(2025, 9, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 84.69m
                        },
                        new
                        {
                            RecordId = new Guid("6d48abb2-f59f-4d45-810f-0a539899fc6a"),
                            CreatedAt = new DateTime(2025, 9, 24, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 24, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 83.38m
                        },
                        new
                        {
                            RecordId = new Guid("abb0c822-e5d2-4202-8db5-31987adc5396"),
                            CreatedAt = new DateTime(2025, 9, 27, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 27, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 82.06m
                        },
                        new
                        {
                            RecordId = new Guid("ad96e545-2a10-4313-8cc5-a040054394ef"),
                            CreatedAt = new DateTime(2025, 9, 30, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 9, 30, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 82.74m
                        },
                        new
                        {
                            RecordId = new Guid("b8589ec9-4125-4634-9f29-4fa9a375557b"),
                            CreatedAt = new DateTime(2025, 10, 3, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 3, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 81.43m
                        },
                        new
                        {
                            RecordId = new Guid("9868dd98-2a52-45d1-b88e-cedfc5d232d7"),
                            CreatedAt = new DateTime(2025, 10, 6, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 6, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 82.11m
                        },
                        new
                        {
                            RecordId = new Guid("1229d529-4d82-438b-87c7-2ee9da82cb3b"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 80.80m
                        },
                        new
                        {
                            RecordId = new Guid("528f7530-a3e7-45c8-b713-528c40fdbc7f"),
                            CreatedAt = new DateTime(2025, 10, 12, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 12, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 81.48m
                        },
                        new
                        {
                            RecordId = new Guid("126c7ecc-864e-4c18-8f61-3c7505855dc5"),
                            CreatedAt = new DateTime(2025, 10, 15, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 15, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 80.17m
                        },
                        new
                        {
                            RecordId = new Guid("f88ba2cd-4eaa-4132-bb00-37a76e2d69fa"),
                            CreatedAt = new DateTime(2025, 10, 18, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 18, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 78.85m
                        },
                        new
                        {
                            RecordId = new Guid("e69838be-3d11-4c9c-9d27-098aa066bb97"),
                            CreatedAt = new DateTime(2025, 10, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 79.54m
                        },
                        new
                        {
                            RecordId = new Guid("a9b3ae4e-f41b-4d6c-b5f7-39df4eaf6d7a"),
                            CreatedAt = new DateTime(2025, 10, 24, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 24, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 78.22m
                        },
                        new
                        {
                            RecordId = new Guid("b53e1b2a-64e7-4aed-8479-cdd755732699"),
                            CreatedAt = new DateTime(2025, 10, 27, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 27, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 78.91m
                        },
                        new
                        {
                            RecordId = new Guid("4f03c90d-f4c2-4593-82c2-2c1238cebcf7"),
                            CreatedAt = new DateTime(2025, 10, 30, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 10, 30, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 77.59m
                        },
                        new
                        {
                            RecordId = new Guid("9e8902b2-8855-4f94-8e01-85bdd65ce7c1"),
                            CreatedAt = new DateTime(2025, 11, 2, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 2, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 78.27m
                        },
                        new
                        {
                            RecordId = new Guid("2aa53006-ca99-4631-908a-260af72a9bc2"),
                            CreatedAt = new DateTime(2025, 11, 5, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 5, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 76.96m
                        },
                        new
                        {
                            RecordId = new Guid("4fe3b273-2d2e-4175-8120-1e389ae038e9"),
                            CreatedAt = new DateTime(2025, 11, 8, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 8, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 75.64m
                        },
                        new
                        {
                            RecordId = new Guid("74543df7-837a-421f-a384-a53a0f457773"),
                            CreatedAt = new DateTime(2025, 11, 11, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 11, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 76.33m
                        },
                        new
                        {
                            RecordId = new Guid("ee1152d0-1cb9-491d-9612-b56bdbbc75bf"),
                            CreatedAt = new DateTime(2025, 11, 14, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 14, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 75.01m
                        },
                        new
                        {
                            RecordId = new Guid("a8b90b52-20da-4f31-8779-ce7e7664b902"),
                            CreatedAt = new DateTime(2025, 11, 17, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 17, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 75.70m
                        },
                        new
                        {
                            RecordId = new Guid("4e07d982-42e8-4ce7-9f33-a494a1ea62fb"),
                            CreatedAt = new DateTime(2025, 11, 20, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 20, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 74.38m
                        },
                        new
                        {
                            RecordId = new Guid("8134a2bc-fac8-4381-a49f-9e68fcaeadc7"),
                            CreatedAt = new DateTime(2025, 11, 23, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 23, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 75.07m
                        },
                        new
                        {
                            RecordId = new Guid("e9a9936c-ad70-42b0-90e1-d8a98c253986"),
                            CreatedAt = new DateTime(2025, 11, 26, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 26, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 73.75m
                        },
                        new
                        {
                            RecordId = new Guid("a342afbd-81d7-4f95-a259-868a58b41be4"),
                            CreatedAt = new DateTime(2025, 11, 29, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 11, 29, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 72.44m
                        },
                        new
                        {
                            RecordId = new Guid("ebfd7ceb-0ef1-4837-90b5-00085cc97498"),
                            CreatedAt = new DateTime(2025, 12, 2, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 12, 2, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 73.12m
                        },
                        new
                        {
                            RecordId = new Guid("21b080ca-309b-4a1e-a01d-26013a3c77cc"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            Height = 175m,
                            RecordDate = new DateTime(2025, 12, 5, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7328),
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            Weight = 71.80m
                        },
                        new
                        {
                            RecordId = new Guid("c8dc97e3-9a0b-468c-9308-afbf6a1bfaca"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 67.68m
                        },
                        new
                        {
                            RecordId = new Guid("b3b65953-352c-4c92-86e0-b7897a315a85"),
                            CreatedAt = new DateTime(2025, 10, 13, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 13, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 68.13m
                        },
                        new
                        {
                            RecordId = new Guid("8d1ff8f6-6726-462a-9002-1d301b690c05"),
                            CreatedAt = new DateTime(2025, 10, 17, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 17, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 68.59m
                        },
                        new
                        {
                            RecordId = new Guid("4c86f72b-d740-4103-8878-ccf7be34f8fd"),
                            CreatedAt = new DateTime(2025, 10, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 69.04m
                        },
                        new
                        {
                            RecordId = new Guid("91daaaee-c1f8-4e33-a3c3-4be376249c07"),
                            CreatedAt = new DateTime(2025, 10, 25, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 25, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 69.50m
                        },
                        new
                        {
                            RecordId = new Guid("518e1b8b-15ea-4e4a-a4a1-3c56217cd35d"),
                            CreatedAt = new DateTime(2025, 10, 29, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 10, 29, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 69.95m
                        },
                        new
                        {
                            RecordId = new Guid("28e7d487-55d8-4af6-ba66-739806af9a6e"),
                            CreatedAt = new DateTime(2025, 11, 2, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 2, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 70.40m
                        },
                        new
                        {
                            RecordId = new Guid("4a18765d-c487-4e1a-8cc1-00e4df7af388"),
                            CreatedAt = new DateTime(2025, 11, 6, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 6, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 70.86m
                        },
                        new
                        {
                            RecordId = new Guid("baec3dee-fbd8-45bd-9bcb-864a2c0558a0"),
                            CreatedAt = new DateTime(2025, 11, 10, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 10, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 71.31m
                        },
                        new
                        {
                            RecordId = new Guid("d2ce4431-ad84-46bc-853b-1bc8a5dfab77"),
                            CreatedAt = new DateTime(2025, 11, 14, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 14, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 71.77m
                        },
                        new
                        {
                            RecordId = new Guid("d467eed2-1d82-4037-888d-7b7125828238"),
                            CreatedAt = new DateTime(2025, 11, 18, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 18, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 70.72m
                        },
                        new
                        {
                            RecordId = new Guid("e52595dd-9441-4ef7-a081-b14134490fbc"),
                            CreatedAt = new DateTime(2025, 11, 22, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 22, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 71.18m
                        },
                        new
                        {
                            RecordId = new Guid("08bc6788-671e-4ab4-9610-7708a746233c"),
                            CreatedAt = new DateTime(2025, 11, 26, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 26, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 71.63m
                        },
                        new
                        {
                            RecordId = new Guid("560a4446-188a-4ba4-ad7b-45d55f7a5a80"),
                            CreatedAt = new DateTime(2025, 11, 30, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 11, 30, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 72.09m
                        },
                        new
                        {
                            RecordId = new Guid("7e233783-fcb8-40d1-bbe0-66a23866ac12"),
                            CreatedAt = new DateTime(2025, 12, 4, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            Height = 165m,
                            RecordDate = new DateTime(2025, 12, 4, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7779),
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            Weight = 72.54m
                        },
                        new
                        {
                            RecordId = new Guid("d01b032f-af7c-44ee-86c6-b606730f76a4"),
                            CreatedAt = new DateTime(2025, 11, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 92.99m
                        },
                        new
                        {
                            RecordId = new Guid("d1666102-064a-48de-b8c9-8150073f272a"),
                            CreatedAt = new DateTime(2025, 11, 11, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 11, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 92.60m
                        },
                        new
                        {
                            RecordId = new Guid("902ba6ea-891f-4554-9b47-cfef750c0910"),
                            CreatedAt = new DateTime(2025, 11, 13, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 13, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 92.22m
                        },
                        new
                        {
                            RecordId = new Guid("85476378-09b8-4bf7-aeaa-994cce41f69e"),
                            CreatedAt = new DateTime(2025, 11, 15, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 15, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 91.83m
                        },
                        new
                        {
                            RecordId = new Guid("5e1151d4-59fc-4d11-ac33-820bf5adcc18"),
                            CreatedAt = new DateTime(2025, 11, 17, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 17, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 91.44m
                        },
                        new
                        {
                            RecordId = new Guid("648d5644-48ab-4f02-8783-423730b1b7ba"),
                            CreatedAt = new DateTime(2025, 11, 19, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 19, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 91.05m
                        },
                        new
                        {
                            RecordId = new Guid("6be58f08-7b74-4b13-bcc9-5b6e7ec97d57"),
                            CreatedAt = new DateTime(2025, 11, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 21, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 90.66m
                        },
                        new
                        {
                            RecordId = new Guid("4e5e7a20-4160-44e1-aa86-bdc6570574c5"),
                            CreatedAt = new DateTime(2025, 11, 23, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 23, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 90.28m
                        },
                        new
                        {
                            RecordId = new Guid("2354dba2-8c9d-49e3-a133-c846ae4aab12"),
                            CreatedAt = new DateTime(2025, 11, 25, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 25, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 89.89m
                        },
                        new
                        {
                            RecordId = new Guid("cfd80b9d-ca5f-46df-9fee-9d4fb9dd705c"),
                            CreatedAt = new DateTime(2025, 11, 27, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 27, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 89.50m
                        },
                        new
                        {
                            RecordId = new Guid("bf480327-e32f-4957-a1bc-56752c94d713"),
                            CreatedAt = new DateTime(2025, 11, 29, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 11, 29, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 86.61m
                        },
                        new
                        {
                            RecordId = new Guid("db4c16ed-6e84-4f9f-b540-c931a90a1626"),
                            CreatedAt = new DateTime(2025, 12, 1, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 1, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 86.23m
                        },
                        new
                        {
                            RecordId = new Guid("67a7ac25-bbbd-41ce-a0e3-2a0d6041e61d"),
                            CreatedAt = new DateTime(2025, 12, 3, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 3, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 85.84m
                        },
                        new
                        {
                            RecordId = new Guid("89cb674b-3cd1-4700-bc40-1f8b0e8f70ff"),
                            CreatedAt = new DateTime(2025, 12, 5, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 5, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 85.45m
                        },
                        new
                        {
                            RecordId = new Guid("ae7cc1ad-de17-4585-9370-fa92364cbbf7"),
                            CreatedAt = new DateTime(2025, 12, 7, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            Height = 182m,
                            RecordDate = new DateTime(2025, 12, 7, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(8035),
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            Weight = 85.06m
                        });
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4e90aca6-37a0-4009-a279-33a36e7338b9"),
                            CreatedAt = new DateTime(2025, 6, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7032),
                            Email = "john.doe@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$wb5n/ECuibV82Nb4tYC//eRkvQ7uakiKp9RuIJ/Qvt0fZEG92p0mm",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserId = new Guid("0e68ba0c-82a9-4dda-bf9d-e17a1e375e84"),
                            CreatedAt = new DateTime(2025, 8, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7046),
                            Email = "jane.smith@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$wb5n/ECuibV82Nb4tYC//eRkvQ7uakiKp9RuIJ/Qvt0fZEG92p0mm",
                            Username = "jane_smith"
                        },
                        new
                        {
                            UserId = new Guid("75990162-7a25-4a8c-98ce-e69bd2fd44b7"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7047),
                            Email = "mike.johnson@example.com",
                            IsAdmin = false,
                            PasswordHash = "$2a$11$wb5n/ECuibV82Nb4tYC//eRkvQ7uakiKp9RuIJ/Qvt0fZEG92p0mm",
                            Username = "mike_johnson"
                        },
                        new
                        {
                            UserId = new Guid("a86c8a38-b2e5-40af-8597-e0a8cf973f89"),
                            CreatedAt = new DateTime(2025, 11, 9, 10, 9, 29, 994, DateTimeKind.Utc).AddTicks(7048),
                            Email = "admin@email.com",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$wb5n/ECuibV82Nb4tYC//eRkvQ7uakiKp9RuIJ/Qvt0fZEG92p0mm",
                            Username = "admin_user"
                        });
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.VersionInfo", b =>
                {
                    b.Property<int>("VersionInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("VersionInfoId");

                    b.ToTable("VersionHistory");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("WeightTracker.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeightTracker.Domain.Entities.Records", b =>
                {
                    b.HasOne("WeightTracker.Domain.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
